config/routes.rb
# frozen_string_literal: true

require 'sidekiq_unique_jobs/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  # Paths of routes on the web app that to not require to be indexed or
  # have alternative format representations requiring separate controllers
  web_app_paths = %w(
    /getting-started
    /keyboard-shortcuts
    /home
    /public
    /public/local
    /public/remote
    /conversations
    /lists/(*any)
    /notifications
    /favourites
    /bookmarks
    /pinned
    /start
    /directory
    /explore/(*any)
    /search
    /publish
    /follow_requests
    /blocks
    /domain_blocks
    /mutes
    /followed_tags
    /statuses/(*any)
    /deck/(*any)
  ).freeze

  root 'home#index'

  mount LetterOpenerWeb::Engine, at: 'letter_opener' if Rails.env.development?

  get 'health', to: 'health#show'

  authenticate :user, lambda { |u| u.role&.can?(:view_devops) } do
    mount Sidekiq::Web, at: 'sidekiq', as: :sidekiq
    mount PgHero::Engine, at: 'pghero', as: :pghero
  end

  use_doorkeeper do
    controllers authorizations: 'oauth/authorizations',
                authorized_applications: 'oauth/authorized_applications',
                tokens: 'oauth/tokens'
  end

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/nodeinfo', to: 'well_known/nodeinfo#index', as: :nodeinfo, defaults: { format: 'json' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger
  get '.well-known/change-password', to: redirect('/auth/edit')

  get '/nodeinfo/2.0', to: 'well_known/nodeinfo#show', as: :nodeinfo_schema

  get 'manifest', to: 'manifests#show', defaults: { format: 'json' }
  get 'intent', to: 'intents#show'
  get 'custom.css', to: 'custom_css#show', as: :custom_css

  resource :instance_actor, path: 'actor', only: [:show] do
    resource :inbox, only: [:create], module: :activitypub
    resource :outbox, only: [:show], module: :activitypub
  end

  devise_scope :user do
    get '/invite/:invite_code', to: 'auth/registrations#new', as: :public_invite

    resource :unsubscribe, only: [:show, :create], controller: :mail_subscriptions

    namespace :auth do
      resource :setup, only: [:show, :update], controller: :setup
      resource :challenge, only: [:create], controller: :challenges
      get 'sessions/security_key_options', to: 'sessions#webauthn_options'
      post 'captcha_confirmation', to: 'confirmations#confirm_captcha', as: :captcha_confirmation
    end
  end

  devise_for :users, path: 'auth', format: false, controllers: {
    omniauth_callbacks: 'auth/omniauth_callbacks',
    sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    passwords:          'auth/passwords',
    confirmations:      'auth/confirmations',
  }

  get '/users/:username', to: redirect('/@%{username}'), constraints: lambda { |req| req.format.nil? || req.format.html? }
  get '/users/:username/following', to: redirect('/@%{username}/following'), constraints: lambda { |req| req.format.nil? || req.format.html? }
  get '/users/:username/followers', to: redirect('/@%{username}/followers'), constraints: lambda { |req| req.format.nil? || req.format.html? }
  get '/users/:username/statuses/:id', to: redirect('/@%{username}/%{id}'), constraints: lambda { |req| req.format.nil? || req.format.html? }
  get '/authorize_follow', to: redirect { |_, request| "/authorize_interaction?#{request.params.to_query}" }

  resources :accounts, path: 'users', only: [:show], param: :username do
    resources :statuses, only: [:show] do
      member do
        get :activity
        get :embed
      end

      resources :replies, only: [:index], module: :activitypub
    end

    resources :followers, only: [:index], controller: :follower_accounts
    resources :following, only: [:index], controller: :following_accounts

    resource :outbox, only: [:show], module: :activitypub
    resource :inbox, only: [:create], module: :activitypub
    resource :claim, only: [:create], module: :activitypub
    resources :collections, only: [:show], module: :activitypub
    resource :followers_synchronization, only: [:show], module: :activitypub
  end

  resource :inbox, only: [:create], module: :activitypub

  get '/:encoded_at(*path)', to: redirect("/@%{path}"), constraints: { encoded_at: /%40/ }

  constraints(username: %r{[^@/.]+}) do
    get '/@:username', to: 'accounts#show', as: :short_account
    get '/@:username/with_replies', to: 'accounts#show', as: :short_account_with_replies
    get '/@:username/media', to: 'accounts#show', as: :short_account_media
    get '/@:username/tagged/:tag', to: 'accounts#show', as: :short_account_tag
  end

  constraints(account_username: %r{[^@/.]+}) do
    get '/@:account_username/following', to: 'following_accounts#index'
    get '/@:account_username/followers', to: 'follower_accounts#index'
    get '/@:account_username/:id', to: 'statuses#show', as: :short_account_status
    get '/@:account_username/:id/embed', to: 'statuses#embed', as: :embed_short_account_status
  end

  get '/@:username_with_domain/(*any)', to: 'home#index', constraints: { username_with_domain: %r{([^/])+?} }, format: false
  get '/settings', to: redirect('/settings/profile')

  draw(:settings)

  namespace :disputes do
    resources :strikes, only: [:show, :index] do
      resource :appeal, only: [:create]
    end
  end

  resources :media, only: [:show] do
    get :player
  end

  resources :tags,   only: [:show]
  resources :emojis, only: [:show]
  resources :invites, only: [:index, :create, :destroy]
  resources :filters, except: [:show] do
    resources :statuses, only: [:index], controller: 'filters/statuses' do
      collection do
        post :batch
      end
    end
  end

  resource :relationships, only: [:show, :update]
  resource :statuses_cleanup, controller: :statuses_cleanup, only: [:show, :update]

  get '/media_proxy/:id/(*any)', to: 'media_proxy#show', as: :media_proxy, format: false
  get '/backups/:id/download', to: 'backups#download', as: :download_backup, format: false

  resource :authorize_interaction, only: [:show, :create]
  resource :share, only: [:show]

  draw(:admin)

  get '/admin', to: redirect('/admin/dashboard', status: 302)

  draw(:api)

  web_app_paths.each do |path|
    get path, to: 'home#index'
  end

  get '/web/(*any)', to: redirect('/%{any}', status: 302), as: :web, defaults: { any: '' }, format: false
  get '/about',      to: 'about#show'
  get '/about/more', to: redirect('/about')

  get '/privacy-policy', to: 'privacy#show', as: :privacy_policy
  get '/terms',          to: redirect('/privacy-policy')

  match '/', via: [:post, :put, :patch, :delete], to: 'application#raise_not_found', format: false
  match '*unmatched_route', via: :all, to: 'application#raise_not_found', format: false
end

app/controllers/api/v1/filters_controller.rb
# frozen_string_literal: true

class Api::V1::FiltersController < Api::BaseController
  before_action -> { doorkeeper_authorize! :read, :'read:filters' }, only: [:index, :show]
  before_action -> { doorkeeper_authorize! :write, :'write:filters' }, except: [:index, :show]
  before_action :require_user!
  before_action :set_filters, only: :index
  before_action :set_filter, only: [:show, :update, :destroy]

  def index
    render json: @filters, each_serializer: REST::V1::FilterSerializer
  end

  def show
    render json: @filter, serializer: REST::V1::FilterSerializer
  end

  def create
    ApplicationRecord.transaction do
      filter_category = current_account.custom_filters.create!(filter_params)
      @filter = filter_category.keywords.create!(keyword_params)
    end

    render json: @filter, serializer: REST::V1::FilterSerializer
  end

  def update
    ApplicationRecord.transaction do
      @filter.update!(keyword_params)
      @filter.custom_filter.assign_attributes(filter_params)
      raise Mastodon::ValidationError, I18n.t('filters.errors.deprecated_api_multiple_keywords') if @filter.custom_filter.changed? && @filter.custom_filter.keywords.count > 1

      @filter.custom_filter.save!
    end

    render json: @filter, serializer: REST::V1::FilterSerializer
  end

  def destroy
    @filter.destroy!
    render_empty
  end

  private

  def set_filters
    @filters = CustomFilterKeyword.includes(:custom_filter).where(custom_filter: { account: current_account })
  end

  def set_filter
    @filter = CustomFilterKeyword.includes(:custom_filter).where(custom_filter: { account: current_account }).find(params[:id])
  end

  def resource_params
    params.permit(:phrase, :expires_in, :irreversible, :whole_word, context: [])
  end

  def filter_params
    resource_params.slice(:phrase, :expires_in, :irreversible, :context)
  end

  def keyword_params
    resource_params.slice(:phrase, :whole_word)
  end
end

app/controllers/api/v2/filters/keywords_controller.rb
# frozen_string_literal: true

class Api::V2::Filters::KeywordsController < Api::BaseController
  before_action -> { doorkeeper_authorize! :read, :'read:filters' }, only: [:index, :show]
  before_action -> { doorkeeper_authorize! :write, :'write:filters' }, except: [:index, :show]
  before_action :require_user!

  before_action :set_keywords, only: :index
  before_action :set_keyword, only: [:show, :update, :destroy]

  def index
    render json: @keywords, each_serializer: REST::FilterKeywordSerializer
  end

  def show
    render json: @keyword, serializer: REST::FilterKeywordSerializer
  end

  def create
    @keyword = current_account.custom_filters.find(params[:filter_id]).keywords.create!(resource_params)

    render json: @keyword, serializer: REST::FilterKeywordSerializer
  end

  def update
    @keyword.update!(resource_params)

    render json: @keyword, serializer: REST::FilterKeywordSerializer
  end

  def destroy
    @keyword.destroy!
    render_empty
  end

  private

  def set_keywords
    filter = current_account.custom_filters.includes(:keywords).find(params[:filter_id])
    @keywords = filter.keywords
  end

  def set_keyword
    @keyword = CustomFilterKeyword.includes(:custom_filter).where(custom_filter: { account: current_account }).find(params[:id])
  end

  def resource_params
    params.permit(:keyword, :whole_word)
  end
end

app/controllers/api/v2/filters/statuses_controller.rb
# frozen_string_literal: true

class Api::V2::Filters::StatusesController < Api::BaseController
  before_action -> { doorkeeper_authorize! :read, :'read:filters' }, only: [:index, :show]
  before_action -> { doorkeeper_authorize! :write, :'write:filters' }, except: [:index, :show]
  before_action :require_user!

  before_action :set_status_filters, only: :index
  before_action :set_status_filter, only: [:show, :destroy]

  def index
    render json: @status_filters, each_serializer: REST::FilterStatusSerializer
  end

  def show
    render json: @status_filter, serializer: REST::FilterStatusSerializer
  end

  def create
    @status_filter = current_account.custom_filters.find(params[:filter_id]).statuses.create!(resource_params)

    render json: @status_filter, serializer: REST::FilterStatusSerializer
  end

  def destroy
    @status_filter.destroy!
    render_empty
  end

  private

  def set_status_filters
    filter = current_account.custom_filters.includes(:statuses).find(params[:filter_id])
    @status_filters = filter.statuses
  end

  def set_status_filter
    @status_filter = CustomFilterStatus.includes(:custom_filter).where(custom_filter: { account: current_account }).find(params[:id])
  end

  def resource_params
    params.permit(:status_id)
  end
end

app/controllers/api/v2/filters_controller.rb
# frozen_string_literal: true

class Api::V2::FiltersController < Api::BaseController
  before_action -> { doorkeeper_authorize! :read, :'read:filters' }, only: [:index, :show]
  before_action -> { doorkeeper_authorize! :write, :'write:filters' }, except: [:index, :show]
  before_action :require_user!
  before_action :set_filters, only: :index
  before_action :set_filter, only: [:show, :update, :destroy]

  def index
    render json: @filters, each_serializer: REST::FilterSerializer, rules_requested: true
  end

  def show
    render json: @filter, serializer: REST::FilterSerializer, rules_requested: true
  end

  def create
    @filter = current_account.custom_filters.create!(resource_params)

    render json: @filter, serializer: REST::FilterSerializer, rules_requested: true
  end

  def update
    @filter.update!(resource_params)

    render json: @filter, serializer: REST::FilterSerializer, rules_requested: true
  end

  def destroy
    @filter.destroy!
    render_empty
  end

  private

  def set_filters
    @filters = current_account.custom_filters.includes(:keywords)
  end

  def set_filter
    @filter = current_account.custom_filters.find(params[:id])
  end

  def resource_params
    params.permit(:title, :expires_in, :filter_action, context: [], keywords_attributes: [:id, :keyword, :whole_word, :_destroy])
  end
end

app/controllers/filters/statuses_controller.rb
# frozen_string_literal: true

class Filters::StatusesController < ApplicationController
  layout 'admin'

  before_action :authenticate_user!
  before_action :set_filter
  before_action :set_status_filters
  before_action :set_body_classes
  before_action :set_cache_headers

  PER_PAGE = 20

  def index
    @status_filter_batch_action = Form::StatusFilterBatchAction.new
  end

  def batch
    @status_filter_batch_action = Form::StatusFilterBatchAction.new(status_filter_batch_action_params.merge(current_account: current_account, filter_id: params[:filter_id], type: action_from_button))
    @status_filter_batch_action.save!
  rescue ActionController::ParameterMissing
    flash[:alert] = I18n.t('admin.statuses.no_status_selected')
  ensure
    redirect_to edit_filter_path(@filter)
  end

  private

  def set_filter
    @filter = current_account.custom_filters.find(params[:filter_id])
  end

  def set_status_filters
    @status_filters = @filter.statuses.preload(:status).page(params[:page]).per(PER_PAGE)
  end

  def status_filter_batch_action_params
    params.require(:form_status_filter_batch_action).permit(status_filter_ids: [])
  end

  def action_from_button
    'remove' if params[:remove]
  end

  def set_body_classes
    @body_classes = 'admin'
  end

  def set_cache_headers
    response.cache_control.replace(private: true, no_store: true)
  end
end

app/controllers/filters_controller.rb
# frozen_string_literal: true

class FiltersController < ApplicationController
  layout 'admin'

  before_action :authenticate_user!
  before_action :set_filter, only: [:edit, :update, :destroy]
  before_action :set_body_classes
  before_action :set_cache_headers

  def index
    @filters = current_account.custom_filters.includes(:keywords, :statuses).order(:phrase)
  end

  def new
    @filter = current_account.custom_filters.build(action: :warn)
    @filter.keywords.build
  end

  def edit; end

  def create
    @filter = current_account.custom_filters.build(resource_params)

    if @filter.save
      redirect_to filters_path
    else
      render action: :new
    end
  end

  def update
    if @filter.update(resource_params)
      redirect_to filters_path
    else
      render action: :edit
    end
  end

  def destroy
    @filter.destroy
    redirect_to filters_path
  end

  private

  def set_filter
    @filter = current_account.custom_filters.find(params[:id])
  end

  def resource_params
    params.require(:custom_filter).permit(:title, :expires_in, :filter_action, context: [], keywords_attributes: [:id, :keyword, :whole_word, :_destroy])
  end

  def set_body_classes
    @body_classes = 'admin'
  end

  def set_cache_headers
    response.cache_control.replace(private: true, no_store: true)
  end
end

app/helpers/admin/filter_helper.rb
# frozen_string_literal: true

module Admin::FilterHelper
  FILTERS = [
    AccountFilter::KEYS,
    CustomEmojiFilter::KEYS,
    ReportFilter::KEYS,
    Trends::TagFilter::KEYS,
    Trends::PreviewCardProviderFilter::KEYS,
    Trends::PreviewCardFilter::KEYS,
    Trends::StatusFilter::KEYS,
    InstanceFilter::KEYS,
    InviteFilter::KEYS,
    RelationshipFilter::KEYS,
    AnnouncementFilter::KEYS,
    Admin::ActionLogFilter::KEYS,
    Admin::StatusFilter::KEYS,
  ].flatten.freeze

  def filter_link_to(text, link_to_params, link_class_params = link_to_params)
    new_url   = filtered_url_for(link_to_params)
    new_class = filtered_url_for(link_class_params)

    link_to text, new_url, class: filter_link_class(new_class)
  end

  def table_link_to(icon, text, path, **options)
    link_to safe_join([fa_icon(icon), text]), path, options.merge(class: 'table-action-link')
  end

  def selected?(more_params)
    new_url = filtered_url_for(more_params)
    filter_link_class(new_url) == 'selected'
  end

  private

  def filter_params(more_params)
    controller_request_params.merge(more_params)
  end

  def filter_link_class(new_url)
    filtered_url_for(controller_request_params) == new_url ? 'selected' : ''
  end

  def filtered_url_for(url_params)
    url_for filter_params(url_params)
  end

  def controller_request_params
    params.permit(FILTERS)
  end
end

app/views/filters/_filter.html.haml
.filters-list__item{ class: [filter.expired? && 'expired'] }
  = link_to edit_filter_path(filter), class: 'filters-list__item__title' do
    = filter.title

    - if filter.expires?
      .expiration{ title: t('filters.index.expires_on', date: l(filter.expires_at)) }
        - if filter.expired?
          = t('invites.expired')
        - else
          = t('filters.index.expires_in', distance: distance_of_time_in_words_to_now(filter.expires_at))

  .filters-list__item__permissions
    %ul.permissions-list
      - unless filter.keywords.empty?
        %li.permissions-list__item
          .permissions-list__item__icon
            = fa_icon('paragraph')
          .permissions-list__item__text
            .permissions-list__item__text__title
              = t('filters.index.keywords', count: filter.keywords.size)
            .permissions-list__item__text__type
              - keywords = filter.keywords.map(&:keyword)
              - keywords = keywords.take(5) + ['…'] if keywords.size > 5 # TODO
              = keywords.join(', ')
      - unless filter.statuses.empty?
        %li.permissions-list__item
          .permissions-list__item__icon
            = fa_icon('comment')
          .permissions-list__item__text
            .permissions-list__item__text__title
              = t('filters.index.statuses', count: filter.statuses.size)
            .permissions-list__item__text__type
              = t('filters.index.statuses_long', count: filter.statuses.size)

  .announcements-list__item__action-bar
    .announcements-list__item__meta
      = t('filters.index.contexts', contexts: filter.context.map { |context| I18n.t("filters.contexts.#{context}") }.join(', '))

    %div
      = table_link_to 'pencil', t('filters.edit.title'), edit_filter_path(filter)
      = table_link_to 'times', t('filters.index.delete'), filter_path(filter), method: :delete, data: { confirm: t('admin.accounts.are_you_sure') }

app/views/filters/_filter_fields.html.haml
.fields-row
  .fields-row__column.fields-row__column-6.fields-group
    = f.input :title, as: :string, wrapper: :with_label, hint: false
  .fields-row__column.fields-row__column-6.fields-group
    = f.input :expires_in, wrapper: :with_label, collection: [30.minutes, 1.hour, 6.hours, 12.hours, 1.day, 1.week].map(&:to_i), label_method: lambda { |i| I18n.t("invites.expires_in.#{i}") }, include_blank: I18n.t('invites.expires_in_prompt')

.fields-group
  = f.input :context, wrapper: :with_block_label, collection: CustomFilter::VALID_CONTEXTS, as: :check_boxes, collection_wrapper_tag: 'ul', item_wrapper_tag: 'li', label_method: lambda { |context| I18n.t("filters.contexts.#{context}") }, include_blank: false

%hr.spacer/

.fields-group
  = f.input :filter_action, as: :radio_buttons, collection: %i(warn hide), include_blank: false, wrapper: :with_block_label, label_method: ->(action) { safe_join([t("simple_form.labels.filters.actions.#{action}"), content_tag(:span, t("simple_form.hints.filters.actions.#{action}"), class: 'hint')]) }, hint: t('simple_form.hints.filters.action'), required: true

%hr.spacer/

- unless f.object.statuses.empty?
  %h4= t('filters.edit.statuses')

  %p.muted-hint= t('filters.edit.statuses_hint_html', path: filter_statuses_path(f.object))

  %hr.spacer/

%h4= t('filters.edit.keywords')

.table-wrapper
  %table.table.keywords-table
    %thead
      %tr
        %th= t('simple_form.labels.defaults.phrase')
        %th= t('simple_form.labels.defaults.whole_word')
        %th
    %tbody
      = f.simple_fields_for :keywords do |keyword|
        = render 'keyword_fields', f: keyword
    %tfoot
      %tr
        %td{ colspan: 3 }
          = link_to_add_association f, :keywords, class: 'table-action-link', partial: 'keyword_fields', 'data-association-insertion-node': '.keywords-table tbody', 'data-association-insertion-method': 'append' do
            = safe_join([fa_icon('plus'), t('filters.edit.add_keyword')])

app/views/filters/_keyword_fields.html.haml
%tr.nested-fields
  %td= f.input :keyword, as: :string
  %td
    .label_input__wrapper= f.input_field :whole_word
  %td
    = f.hidden_field :id if f.object&.persisted? # Required so Rails doesn't put the field outside of the <tr/>
    = link_to_remove_association(f, class: 'table-action-link') do
      = safe_join([fa_icon('times'), t('filters.index.delete')])

app/views/filters/edit.html.haml
- content_for :page_title do
  = t('filters.edit.title')

= simple_form_for @filter, url: filter_path(@filter), method: :put do |f|
  = render 'filter_fields', f: f

  .actions
    = f.button :button, t('generic.save_changes'), type: :submit

app/views/filters/index.html.haml
- content_for :page_title do
  = t('filters.index.title')

- content_for :heading_actions do
  = link_to t('filters.new.title'), new_filter_path, class: 'button'

- if @filters.empty?
  .muted-hint.center-text= t 'filters.index.empty'
- else
  .applications-list
    = render partial: 'filter', collection: @filters

app/views/filters/new.html.haml
- content_for :page_title do
  = t('filters.new.title')

= simple_form_for @filter, url: filters_path do |f|
  = render 'filter_fields', f: f

  .actions
    = f.button :button, t('filters.new.save'), type: :submit